#!/usr/bin/env bash
# Script to set up an nginx server and create an index.html file

sudo apt-get update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
