#!/usr/bin/env bash
# Script to handle redirects

FILE_PATH="/etc/nginx/sites-available/default"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/killianthakyo; \n\t}\n"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i "54i\ $REDIRECT" "$FILE_PATH"

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
