#!/usr/bin/env bash
# Script to setup an nginx server with custom headers

#!/usr/bin/env bash
# Script to set up custom 404 page

FILE_PATH="/etc/nginx/sites-available/default"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/jumaemm; \n\t}\n"
ERRORFILE="/var/www/html/404.html"
ERROR="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
HEADER="\n\tadd_header X-Served-By $hostname;\n"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i "54i\ $REDIRECT" "$FILE_PATH"

echo "Ceci n'est pas une page" > "$ERRORFILE"
sudo sed -i "54i\ $ERROR" "$FILE_PATH"
sudo sed -i "54i\ $HEADER" "$FILE_PATH"

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
